### ISSUE TITLE
Move adwaitatheme to external package

### ISSUE THREAD

**Issue by MalcolmMielle** [gtk-flutter/gtk-flutter#12]
I think Adwaita theme should be a separate package as is done for [yaru](https://github.com/ubuntu/yaru.dart). That way we could easily update it outside of GTK and other could use the theme in their apps.

We could also add the retro-compat with gtk3 css in it.

Let me know if it's of interest and if you have time to do it otherwise I'll start with that.

**Comment by prateekmedia** [comment]
Interesting, Can you suggest how it would be done, As how would Theme.of(context).tiles will know which tiles color to pick, if there are multiples themes.

**Comment by MalcolmMielle** [comment]
I'm wondering if we really need those specific color attributes? If you look at yaru and yaru_widgets packages, they don't, the theme and widgets are entirely separate things and it's much nicer in terms of designed. Then we could switch to yaru even with gtk element. So i was thinking something more along those lines.

**Comment by prateekmedia** [comment]
Yes, please!

**Comment by MalcolmMielle** [comment]
I'll start the adwaita-theme soon then and then we'll migrate.

**Comment by MalcolmMielle** [comment]
Proposed change in #13
